services:
  czech-anonymization:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - shared-network
    restart: always

  nametag3:
    build:
      context: https://github.com/ZykaJiri/nametag3-docker.git
    ports:
      - "8001:8001"
    networks:
      - shared-network
    restart: always

networks:
  shared-network:
    driver: bridge